- name: Docker repo
  ansible.builtin.yum_repository:
    baseurl: "https://download.docker.com/linux/centos/9/x86_64/stable"
    state: present
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: true
    name: "Docker_CE_Stable_-_x86_64"
    description: "Docker CE Stable - x86_64"
  become: true
  become_user: root
- name: Install iptables-nft
  ansible.builtin.dnf:
    name:
      - iptables-nft
    state: latest
  become: true
  become_user: root
- name: Install Docker
  ansible.builtin.dnf:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-pip
    state: latest
  become: true
  become_user: root
- name: Install Python Docker SDK
  ansible.builtin.pip:
    name:
      - docker
      - requests
    state: present
  become: true
- name: Set up mirror registry
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    src: ./files/daemon.json
  become: true
  become_user: root
- name: Ensure certificate directory
  ansible.builtin.file:
    path: /etc/docker/certs.d
    state: directory
  become: true
  become_user: root
- name: Create directory for cache certificate
  ansible.builtin.file:
    path: "/etc/docker/certs.d/10.134.12.4:4000"
    state: directory
  become: true
  become_user: root
- name: Install cache certificate
  ansible.builtin.copy:
    dest: "/etc/docker/certs.d/10.134.12.4:4000/ca.crt"
    src: ./files/tls.crt
  become: true
  become_user: root
- name: Enable Docker Service
  ansible.builtin.service:
    name: docker
    enabled: true
    state: started
  become: true
  become_user: root
- name: Add almalinux to the docker group
  ansible.builtin.user:
    append: true
    groups: docker
    name: almalinux
  become: true
  become_user: root
#importantï¼Œotherwise it will say not authority
- name: Reset ssh connection to apply new group membership
  meta: reset_connection
- name: Pull Docker image using docker command
  ansible.builtin.shell: docker pull soedinglab/hh-suite:latest