- name: Make sure project root exists
  ansible.builtin.file:
    state: directory
    path: "{{ project_root }}"
    mode: '0755'
  #become: yes
- name: copy pipeline code to workers
  ansible.builtin.copy:
    src: "{{ pipeline_script }}"
    dest: "{{ project_root }}/pipeline_script.py"
  become: true
  become_user: root
- name: copy parser code to workers
  ansible.builtin.copy:
    src: "{{ results_parser }}"
    dest: "{{ project_root }}/results_parser.py"
  become: true 
  become_user: root
