- name: kill celery by pkill
  ansible.builtin.shell: "pkill -o -f 'celery'"
  failed_when: false #忽略错误，即使没有找到进程也不会报错 
- name: wait 1 seconds to ensure celery know the worker is killed
  ansible.builtin.pause:
    seconds: 1