- name: Ensure pip packages are installed for Python 3.12
  ansible.builtin.pip:
    name:
      - numpy
      - scipy
      - biopython
      - celery
      - torch
      - docker
    executable: pip3.12
    state: present
  become: yes 