- name: kill celery by pkill
  ansible.builtin.shell: "pkill -o -f -9 'celery'"
  failed_when: false 
- name: kill HHsearch to prevent from cpu overloadï¼Œsince HHsearch may continue
  ansible.builtin.shell: "pkill -f -9 'hhsearch'"
  failed_when: false 
  become: yes