- name: Ensure pip packages are installed for Python 3.12
  ansible.builtin.pip:
    name:
      - numpy
      - celery
      - redis
      - pandas
    executable: pip3.12
    state: present
  become: yes